// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ArchipelagoData
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "world_id")]
        public ulong WorldId;
        [DataMember(Name = "data")]
        public System.Collections.Generic.List<byte> Data;

        public ArchipelagoData(
            ulong Id,
            ulong WorldId,
            System.Collections.Generic.List<byte> Data
        )
        {
            this.Id = Id;
            this.WorldId = WorldId;
            this.Data = Data;
        }

        public ArchipelagoData()
        {
            this.Data = new();
        }
    }
}
