// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class BehaviorTree
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "behavior")]
        public System.Collections.Generic.List<byte> Behavior;

        public BehaviorTree(
            ulong Id,
            System.Collections.Generic.List<byte> Behavior
        )
        {
            this.Id = Id;
            this.Behavior = Behavior;
        }

        public BehaviorTree()
        {
            this.Behavior = new();
        }
    }
}
