// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Collider
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "world_id")]
        public ulong WorldId;
        [DataMember(Name = "radius")]
        public float Radius;
        [DataMember(Name = "normal")]
        public Vec3 Normal;
        [DataMember(Name = "height")]
        public float Height;
        [DataMember(Name = "size")]
        public Vec3 Size;
        [DataMember(Name = "point_a")]
        public Vec3 PointA;
        [DataMember(Name = "point_b")]
        public Vec3 PointB;
        [DataMember(Name = "point_c")]
        public Vec3 PointC;
        [DataMember(Name = "collider_type")]
        public ColliderType ColliderType;

        public Collider(
            ulong Id,
            ulong WorldId,
            float Radius,
            Vec3 Normal,
            float Height,
            Vec3 Size,
            Vec3 PointA,
            Vec3 PointB,
            Vec3 PointC,
            ColliderType ColliderType
        )
        {
            this.Id = Id;
            this.WorldId = WorldId;
            this.Radius = Radius;
            this.Normal = Normal;
            this.Height = Height;
            this.Size = Size;
            this.PointA = PointA;
            this.PointB = PointB;
            this.PointC = PointC;
            this.ColliderType = ColliderType;
        }

        public Collider()
        {
            this.Normal = new();
            this.Size = new();
            this.PointA = new();
            this.PointB = new();
            this.PointC = new();
        }
    }
}
