// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ExternalNavMesh
    {
        [DataMember(Name = "translation")]
        public Vec3 Translation;
        [DataMember(Name = "rotation")]
        public float Rotation;
        [DataMember(Name = "vertices")]
        public System.Collections.Generic.List<Vec3> Vertices;
        [DataMember(Name = "polygons")]
        public System.Collections.Generic.List<System.Collections.Generic.List<ulong>> Polygons;
        [DataMember(Name = "polygon_type_indices")]
        public System.Collections.Generic.List<ulong> PolygonTypeIndices;

        public ExternalNavMesh(
            Vec3 Translation,
            float Rotation,
            System.Collections.Generic.List<Vec3> Vertices,
            System.Collections.Generic.List<System.Collections.Generic.List<ulong>> Polygons,
            System.Collections.Generic.List<ulong> PolygonTypeIndices
        )
        {
            this.Translation = Translation;
            this.Rotation = Rotation;
            this.Vertices = Vertices;
            this.Polygons = Polygons;
            this.PolygonTypeIndices = PolygonTypeIndices;
        }

        public ExternalNavMesh()
        {
            this.Translation = new();
            this.Vertices = new();
            this.Polygons = new();
            this.PolygonTypeIndices = new();
        }
    }
}
