// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class NavigationAgent
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "world_id")]
        public ulong WorldId;
        [DataMember(Name = "external_id")]
        public ulong? ExternalId;
        [DataMember(Name = "position")]
        public Vec3 Position;
        [DataMember(Name = "velocity")]
        public Vec3 Velocity;
        [DataMember(Name = "current_target")]
        public Vec3? CurrentTarget;
        [DataMember(Name = "state")]
        public NavigationState State;
        [DataMember(Name = "target_reached_condition")]
        public TargetReachedCondition TargetReachedCondition;
        [DataMember(Name = "radius")]
        public float Radius;
        [DataMember(Name = "desired_speed")]
        public float DesiredSpeed;
        [DataMember(Name = "max_speed")]
        public float MaxSpeed;
        [DataMember(Name = "paused")]
        public bool Paused;

        public NavigationAgent(
            ulong Id,
            ulong WorldId,
            ulong? ExternalId,
            Vec3 Position,
            Vec3 Velocity,
            Vec3? CurrentTarget,
            NavigationState State,
            TargetReachedCondition TargetReachedCondition,
            float Radius,
            float DesiredSpeed,
            float MaxSpeed,
            bool Paused
        )
        {
            this.Id = Id;
            this.WorldId = WorldId;
            this.ExternalId = ExternalId;
            this.Position = Position;
            this.Velocity = Velocity;
            this.CurrentTarget = CurrentTarget;
            this.State = State;
            this.TargetReachedCondition = TargetReachedCondition;
            this.Radius = Radius;
            this.DesiredSpeed = DesiredSpeed;
            this.MaxSpeed = MaxSpeed;
            this.Paused = Paused;
        }

        public NavigationAgent()
        {
            this.Position = new();
            this.Velocity = new();
            this.TargetReachedCondition = null!;
        }
    }
}
