// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Player
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "joined_at")]
        public SpacetimeDB.Timestamp JoinedAt;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "position")]
        public Vec3 Position;

        public Player(
            ulong Id,
            SpacetimeDB.Identity Identity,
            SpacetimeDB.Timestamp JoinedAt,
            string Name,
            Vec3 Position
        )
        {
            this.Id = Id;
            this.Identity = Identity;
            this.JoinedAt = JoinedAt;
            this.Name = Name;
            this.Position = Position;
        }

        public Player()
        {
            this.Name = "";
            this.Position = new();
        }
    }
}
