// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class RayCast
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "world_id")]
        public ulong WorldId;
        [DataMember(Name = "origin")]
        public Vec3 Origin;
        [DataMember(Name = "direction")]
        public Vec3 Direction;
        [DataMember(Name = "max_distance")]
        public float MaxDistance;
        [DataMember(Name = "solid")]
        public bool Solid;
        [DataMember(Name = "hits")]
        public System.Collections.Generic.List<RayCastHit> Hits;
        [DataMember(Name = "added_hits")]
        public System.Collections.Generic.List<RayCastHit> AddedHits;
        [DataMember(Name = "removed_hits")]
        public System.Collections.Generic.List<RayCastHit> RemovedHits;

        public RayCast(
            ulong Id,
            ulong WorldId,
            Vec3 Origin,
            Vec3 Direction,
            float MaxDistance,
            bool Solid,
            System.Collections.Generic.List<RayCastHit> Hits,
            System.Collections.Generic.List<RayCastHit> AddedHits,
            System.Collections.Generic.List<RayCastHit> RemovedHits
        )
        {
            this.Id = Id;
            this.WorldId = WorldId;
            this.Origin = Origin;
            this.Direction = Direction;
            this.MaxDistance = MaxDistance;
            this.Solid = Solid;
            this.Hits = Hits;
            this.AddedHits = AddedHits;
            this.RemovedHits = RemovedHits;
        }

        public RayCast()
        {
            this.Origin = new();
            this.Direction = new();
            this.Hits = new();
            this.AddedHits = new();
            this.RemovedHits = new();
        }
    }
}
