// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class RayCastHit
    {
        [DataMember(Name = "distance")]
        public float Distance;
        [DataMember(Name = "position")]
        public Vec3 Position;
        [DataMember(Name = "normal")]
        public Vec3 Normal;
        [DataMember(Name = "rigid_body_id")]
        public ulong RigidBodyId;

        public RayCastHit(
            float Distance,
            Vec3 Position,
            Vec3 Normal,
            ulong RigidBodyId
        )
        {
            this.Distance = Distance;
            this.Position = Position;
            this.Normal = Normal;
            this.RigidBodyId = RigidBodyId;
        }

        public RayCastHit()
        {
            this.Position = new();
            this.Normal = new();
        }
    }
}
