// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class RigidBody
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "world_id")]
        public ulong WorldId;
        [DataMember(Name = "position")]
        public Vec3 Position;
        [DataMember(Name = "rotation")]
        public Quat Rotation;
        [DataMember(Name = "body_type")]
        public RigidBodyType BodyType;
        [DataMember(Name = "collider_id")]
        public ulong ColliderId;

        public RigidBody(
            ulong Id,
            ulong WorldId,
            Vec3 Position,
            Quat Rotation,
            RigidBodyType BodyType,
            ulong ColliderId
        )
        {
            this.Id = Id;
            this.WorldId = WorldId;
            this.Position = Position;
            this.Rotation = Rotation;
            this.BodyType = BodyType;
            this.ColliderId = ColliderId;
        }

        public RigidBody()
        {
            this.Position = new();
            this.Rotation = new();
        }
    }
}
