// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class SpitterAoE
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "trigger_id")]
        public ulong TriggerId;
        [DataMember(Name = "position")]
        public Vec3 Position;
        [DataMember(Name = "delete_at")]
        public SpacetimeDB.Timestamp DeleteAt;
        [DataMember(Name = "scheduled_at")]
        public SpacetimeDB.ScheduleAt ScheduledAt;

        public SpitterAoE(
            ulong Id,
            ulong TriggerId,
            Vec3 Position,
            SpacetimeDB.Timestamp DeleteAt,
            SpacetimeDB.ScheduleAt ScheduledAt
        )
        {
            this.Id = Id;
            this.TriggerId = TriggerId;
            this.Position = Position;
            this.DeleteAt = DeleteAt;
            this.ScheduledAt = ScheduledAt;
        }

        public SpitterAoE()
        {
            this.Position = new();
            this.ScheduledAt = null!;
        }
    }
}
