// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class SpitterZombie
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "navigation_agent_id")]
        public ulong NavigationAgentId;
        [DataMember(Name = "position")]
        public Vec3 Position;
        [DataMember(Name = "target_player")]
        public ulong? TargetPlayer;
        [DataMember(Name = "is_attacking")]
        public bool IsAttacking;
        [DataMember(Name = "next_attack_time")]
        public SpacetimeDB.Timestamp NextAttackTime;

        public SpitterZombie(
            ulong Id,
            ulong NavigationAgentId,
            Vec3 Position,
            ulong? TargetPlayer,
            bool IsAttacking,
            SpacetimeDB.Timestamp NextAttackTime
        )
        {
            this.Id = Id;
            this.NavigationAgentId = NavigationAgentId;
            this.Position = Position;
            this.TargetPlayer = TargetPlayer;
            this.IsAttacking = IsAttacking;
            this.NextAttackTime = NextAttackTime;
        }

        public SpitterZombie()
        {
            this.Position = new();
        }
    }
}
