// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Trigger
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "world_id")]
        public ulong WorldId;
        [DataMember(Name = "position")]
        public Vec3 Position;
        [DataMember(Name = "rotation")]
        public Quat Rotation;
        [DataMember(Name = "collider_id")]
        public ulong ColliderId;
        [DataMember(Name = "entities_inside")]
        public System.Collections.Generic.List<ulong> EntitiesInside;
        [DataMember(Name = "added_entities")]
        public System.Collections.Generic.List<ulong> AddedEntities;
        [DataMember(Name = "removed_entities")]
        public System.Collections.Generic.List<ulong> RemovedEntities;

        public Trigger(
            ulong Id,
            ulong WorldId,
            Vec3 Position,
            Quat Rotation,
            ulong ColliderId,
            System.Collections.Generic.List<ulong> EntitiesInside,
            System.Collections.Generic.List<ulong> AddedEntities,
            System.Collections.Generic.List<ulong> RemovedEntities
        )
        {
            this.Id = Id;
            this.WorldId = WorldId;
            this.Position = Position;
            this.Rotation = Rotation;
            this.ColliderId = ColliderId;
            this.EntitiesInside = EntitiesInside;
            this.AddedEntities = AddedEntities;
            this.RemovedEntities = RemovedEntities;
        }

        public Trigger()
        {
            this.Position = new();
            this.Rotation = new();
            this.EntitiesInside = new();
            this.AddedEntities = new();
            this.RemovedEntities = new();
        }
    }
}
