// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class World
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "navigation_substeps")]
        public ushort NavigationSubsteps;
        [DataMember(Name = "debug")]
        public bool Debug;

        public World(
            ulong Id,
            ushort NavigationSubsteps,
            bool Debug
        )
        {
            this.Id = Id;
            this.NavigationSubsteps = NavigationSubsteps;
            this.Debug = Debug;
        }

        public World()
        {
        }
    }
}
