// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class World
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "debug")]
        public bool Debug;
        [DataMember(Name = "debug_navigation")]
        public bool DebugNavigation;
        [DataMember(Name = "debug_sample_rate")]
        public float DebugSampleRate;

        public World(
            ulong Id,
            bool Debug,
            bool DebugNavigation,
            float DebugSampleRate
        )
        {
            this.Id = Id;
            this.Debug = Debug;
            this.DebugNavigation = DebugNavigation;
            this.DebugSampleRate = DebugSampleRate;
        }

        public World()
        {
        }
    }
}
