// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class World
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "aabb_dilation_factor")]
        public float AabbDilationFactor;
        [DataMember(Name = "debug")]
        public bool Debug;
        [DataMember(Name = "debug_navigation")]
        public bool DebugNavigation;
        [DataMember(Name = "debug_behavior_trees")]
        public bool DebugBehaviorTrees;
        [DataMember(Name = "debug_collisions")]
        public bool DebugCollisions;
        [DataMember(Name = "debug_sample_rate")]
        public float DebugSampleRate;

        public World(
            ulong Id,
            float AabbDilationFactor,
            bool Debug,
            bool DebugNavigation,
            bool DebugBehaviorTrees,
            bool DebugCollisions,
            float DebugSampleRate
        )
        {
            this.Id = Id;
            this.AabbDilationFactor = AabbDilationFactor;
            this.Debug = Debug;
            this.DebugNavigation = DebugNavigation;
            this.DebugBehaviorTrees = DebugBehaviorTrees;
            this.DebugCollisions = DebugCollisions;
            this.DebugSampleRate = DebugSampleRate;
        }

        public World()
        {
        }
    }
}
