// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ZombieSpawnPoint
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "position")]
        public Vec3 Position;

        public ZombieSpawnPoint(
            ulong Id,
            Vec3 Position
        )
        {
            this.Id = Id;
            this.Position = Position;
        }

        public ZombieSpawnPoint()
        {
            this.Position = new();
        }
    }
}
