// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Zombie
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "navigation_agent_id")]
        public ulong NavigationAgentId;
        [DataMember(Name = "position")]
        public Vec3 Position;
        [DataMember(Name = "spawned_at")]
        public SpacetimeDB.Timestamp SpawnedAt;

        public Zombie(
            ulong Id,
            ulong NavigationAgentId,
            Vec3 Position,
            SpacetimeDB.Timestamp SpawnedAt
        )
        {
            this.Id = Id;
            this.NavigationAgentId = NavigationAgentId;
            this.Position = Position;
            this.SpawnedAt = SpawnedAt;
        }

        public Zombie()
        {
            this.Position = new();
        }
    }
}
