// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DummyHandler(ReducerEventContext ctx, ExternalNavMesh en);
        public event DummyHandler? OnDummy;

        public void Dummy(ExternalNavMesh en)
        {
            conn.InternalCallReducer(new Reducer.Dummy(en), this.SetCallReducerFlags.DummyFlags);
        }

        public bool InvokeDummy(ReducerEventContext ctx, Reducer.Dummy args)
        {
            if (OnDummy == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDummy(
                ctx,
                args.En
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class Dummy : Reducer, IReducerArgs
        {
            [DataMember(Name = "_en")]
            public ExternalNavMesh En;

            public Dummy(ExternalNavMesh En)
            {
                this.En = En;
            }

            public Dummy()
            {
                this.En = new();
            }

            string IReducerArgs.ReducerName => "dummy";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags DummyFlags;
        public void Dummy(CallReducerFlags flags) => DummyFlags = flags;
    }
}
