// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void EditorUploadNavmeshHandler(ReducerEventContext ctx, ulong worldId);
        public event EditorUploadNavmeshHandler? OnEditorUploadNavmesh;

        public void EditorUploadNavmesh(ulong worldId)
        {
            conn.InternalCallReducer(new Reducer.EditorUploadNavmesh(worldId), this.SetCallReducerFlags.EditorUploadNavmeshFlags);
        }

        public bool InvokeEditorUploadNavmesh(ReducerEventContext ctx, Reducer.EditorUploadNavmesh args)
        {
            if (OnEditorUploadNavmesh == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnEditorUploadNavmesh(
                ctx,
                args.WorldId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class EditorUploadNavmesh : Reducer, IReducerArgs
        {
            [DataMember(Name = "world_id")]
            public ulong WorldId;

            public EditorUploadNavmesh(ulong WorldId)
            {
                this.WorldId = WorldId;
            }

            public EditorUploadNavmesh()
            {
            }

            string IReducerArgs.ReducerName => "editor_upload_navmesh";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags EditorUploadNavmeshFlags;
        public void EditorUploadNavmesh(CallReducerFlags flags) => EditorUploadNavmeshFlags = flags;
    }
}
