// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void GenerateExternalNavmeshHandler(ReducerEventContext ctx, ExternalNavMesh en);
        public event GenerateExternalNavmeshHandler? OnGenerateExternalNavmesh;

        public void GenerateExternalNavmesh(ExternalNavMesh en)
        {
            conn.InternalCallReducer(new Reducer.GenerateExternalNavmesh(en), this.SetCallReducerFlags.GenerateExternalNavmeshFlags);
        }

        public bool InvokeGenerateExternalNavmesh(ReducerEventContext ctx, Reducer.GenerateExternalNavmesh args)
        {
            if (OnGenerateExternalNavmesh == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnGenerateExternalNavmesh(
                ctx,
                args.En
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class GenerateExternalNavmesh : Reducer, IReducerArgs
        {
            [DataMember(Name = "_en")]
            public ExternalNavMesh En;

            public GenerateExternalNavmesh(ExternalNavMesh En)
            {
                this.En = En;
            }

            public GenerateExternalNavmesh()
            {
                this.En = new();
            }

            string IReducerArgs.ReducerName => "generate_external_navmesh";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags GenerateExternalNavmeshFlags;
        public void GenerateExternalNavmesh(CallReducerFlags flags) => GenerateExternalNavmeshFlags = flags;
    }
}
