// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void PlayerReadyHandler(ReducerEventContext ctx);
        public event PlayerReadyHandler? OnPlayerReady;

        public void PlayerReady()
        {
            conn.InternalCallReducer(new Reducer.PlayerReady(), this.SetCallReducerFlags.PlayerReadyFlags);
        }

        public bool InvokePlayerReady(ReducerEventContext ctx, Reducer.PlayerReady args)
        {
            if (OnPlayerReady == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnPlayerReady(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class PlayerReady : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "player_ready";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags PlayerReadyFlags;
        public void PlayerReady(CallReducerFlags flags) => PlayerReadyFlags = flags;
    }
}
