// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void PlayerUpdatePositionHandler(ReducerEventContext ctx, Vec3 newPosition);
        public event PlayerUpdatePositionHandler? OnPlayerUpdatePosition;

        public void PlayerUpdatePosition(Vec3 newPosition)
        {
            conn.InternalCallReducer(new Reducer.PlayerUpdatePosition(newPosition), this.SetCallReducerFlags.PlayerUpdatePositionFlags);
        }

        public bool InvokePlayerUpdatePosition(ReducerEventContext ctx, Reducer.PlayerUpdatePosition args)
        {
            if (OnPlayerUpdatePosition == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnPlayerUpdatePosition(
                ctx,
                args.NewPosition
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class PlayerUpdatePosition : Reducer, IReducerArgs
        {
            [DataMember(Name = "new_position")]
            public Vec3 NewPosition;

            public PlayerUpdatePosition(Vec3 NewPosition)
            {
                this.NewPosition = NewPosition;
            }

            public PlayerUpdatePosition()
            {
                this.NewPosition = new();
            }

            string IReducerArgs.ReducerName => "player_update_position";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags PlayerUpdatePositionFlags;
        public void PlayerUpdatePosition(CallReducerFlags flags) => PlayerUpdatePositionFlags = flags;
    }
}
