// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SpawnZombiesHandler(ReducerEventContext ctx, ZombieSpawnTick t);
        public event SpawnZombiesHandler? OnSpawnZombies;

        public void SpawnZombies(ZombieSpawnTick t)
        {
            conn.InternalCallReducer(new Reducer.SpawnZombies(t), this.SetCallReducerFlags.SpawnZombiesFlags);
        }

        public bool InvokeSpawnZombies(ReducerEventContext ctx, Reducer.SpawnZombies args)
        {
            if (OnSpawnZombies == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSpawnZombies(
                ctx,
                args.T
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SpawnZombies : Reducer, IReducerArgs
        {
            [DataMember(Name = "_t")]
            public ZombieSpawnTick T;

            public SpawnZombies(ZombieSpawnTick T)
            {
                this.T = T;
            }

            public SpawnZombies()
            {
                this.T = new();
            }

            string IReducerArgs.ReducerName => "spawn_zombies";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags SpawnZombiesFlags;
        public void SpawnZombies(CallReducerFlags flags) => SpawnZombiesFlags = flags;
    }
}
