// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void TickSpitterZombieHandler(ReducerEventContext ctx, SpitterZombieUpdateTick tick);
        public event TickSpitterZombieHandler? OnTickSpitterZombie;

        public void TickSpitterZombie(SpitterZombieUpdateTick tick)
        {
            conn.InternalCallReducer(new Reducer.TickSpitterZombie(tick), this.SetCallReducerFlags.TickSpitterZombieFlags);
        }

        public bool InvokeTickSpitterZombie(ReducerEventContext ctx, Reducer.TickSpitterZombie args)
        {
            if (OnTickSpitterZombie == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnTickSpitterZombie(
                ctx,
                args.Tick
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class TickSpitterZombie : Reducer, IReducerArgs
        {
            [DataMember(Name = "tick")]
            public SpitterZombieUpdateTick Tick;

            public TickSpitterZombie(SpitterZombieUpdateTick Tick)
            {
                this.Tick = Tick;
            }

            public TickSpitterZombie()
            {
                this.Tick = new();
            }

            string IReducerArgs.ReducerName => "tick_spitter_zombie";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags TickSpitterZombieFlags;
        public void TickSpitterZombie(CallReducerFlags flags) => TickSpitterZombieFlags = flags;
    }
}
