// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void TickSpitterAoeHandler(ReducerEventContext ctx, SpitterAoE tick);
        public event TickSpitterAoeHandler? OnTickSpitterAoe;

        public void TickSpitterAoe(SpitterAoE tick)
        {
            conn.InternalCallReducer(new Reducer.TickSpitterAoe(tick), this.SetCallReducerFlags.TickSpitterAoeFlags);
        }

        public bool InvokeTickSpitterAoe(ReducerEventContext ctx, Reducer.TickSpitterAoe args)
        {
            if (OnTickSpitterAoe == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnTickSpitterAoe(
                ctx,
                args.Tick
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class TickSpitterAoe : Reducer, IReducerArgs
        {
            [DataMember(Name = "tick")]
            public SpitterAoE Tick;

            public TickSpitterAoe(SpitterAoE Tick)
            {
                this.Tick = Tick;
            }

            public TickSpitterAoe()
            {
                this.Tick = new();
            }

            string IReducerArgs.ReducerName => "tick_spitter_aoe";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags TickSpitterAoeFlags;
        public void TickSpitterAoe(CallReducerFlags flags) => TickSpitterAoeFlags = flags;
    }
}
