// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void TickWorldHandler(ReducerEventContext ctx, WorldTick tick);
        public event TickWorldHandler? OnTickWorld;

        public void TickWorld(WorldTick tick)
        {
            conn.InternalCallReducer(new Reducer.TickWorld(tick), this.SetCallReducerFlags.TickWorldFlags);
        }

        public bool InvokeTickWorld(ReducerEventContext ctx, Reducer.TickWorld args)
        {
            if (OnTickWorld == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnTickWorld(
                ctx,
                args.Tick
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class TickWorld : Reducer, IReducerArgs
        {
            [DataMember(Name = "tick")]
            public WorldTick Tick;

            public TickWorld(WorldTick Tick)
            {
                this.Tick = Tick;
            }

            public TickWorld()
            {
                this.Tick = new();
            }

            string IReducerArgs.ReducerName => "tick_world";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags TickWorldFlags;
        public void TickWorld(CallReducerFlags flags) => TickWorldFlags = flags;
    }
}
