// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void TickZombieHandler(ReducerEventContext ctx, ZombieUpdateTick t);
        public event TickZombieHandler? OnTickZombie;

        public void TickZombie(ZombieUpdateTick t)
        {
            conn.InternalCallReducer(new Reducer.TickZombie(t), this.SetCallReducerFlags.TickZombieFlags);
        }

        public bool InvokeTickZombie(ReducerEventContext ctx, Reducer.TickZombie args)
        {
            if (OnTickZombie == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnTickZombie(
                ctx,
                args.T
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class TickZombie : Reducer, IReducerArgs
        {
            [DataMember(Name = "_t")]
            public ZombieUpdateTick T;

            public TickZombie(ZombieUpdateTick T)
            {
                this.T = T;
            }

            public TickZombie()
            {
                this.T = new();
            }

            string IReducerArgs.ReducerName => "tick_zombie";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags TickZombieFlags;
        public void TickZombie(CallReducerFlags flags) => TickZombieFlags = flags;
    }
}
