// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class SpitterAoeHandle : RemoteTableHandle<EventContext, SpitterAoE>
        {
            protected override string RemoteTableName => "spitter_aoe";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(SpitterAoE row) => row.Id;

                public IdUniqueIndex(SpitterAoeHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal SpitterAoeHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(SpitterAoE row) => row.Id;
        }

        public readonly SpitterAoeHandle SpitterAoe;
    }
}
