// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class SpitterZombieHandle : RemoteTableHandle<EventContext, SpitterZombie>
        {
            protected override string RemoteTableName => "spitter_zombie";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(SpitterZombie row) => row.Id;

                public IdUniqueIndex(SpitterZombieHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class NavigationAgentIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(SpitterZombie row) => row.NavigationAgentId;

                public NavigationAgentIdIndex(SpitterZombieHandle table) : base(table) { }
            }

            public readonly NavigationAgentIdIndex NavigationAgentId;

            internal SpitterZombieHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                NavigationAgentId = new(this);
            }

            protected override object GetPrimaryKey(SpitterZombie row) => row.Id;
        }

        public readonly SpitterZombieHandle SpitterZombie;
    }
}
