// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class SpitterZombieUpdateTickHandle : RemoteTableHandle<EventContext, SpitterZombieUpdateTick>
        {
            protected override string RemoteTableName => "spitter_zombie_update_tick";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(SpitterZombieUpdateTick row) => row.Id;

                public IdUniqueIndex(SpitterZombieUpdateTickHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal SpitterZombieUpdateTickHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(SpitterZombieUpdateTick row) => row.Id;
        }

        public readonly SpitterZombieUpdateTickHandle SpitterZombieUpdateTick;
    }
}
