// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class StengTriggersHandle : RemoteTableHandle<EventContext, Trigger>
        {
            protected override string RemoteTableName => "steng_triggers";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Trigger row) => row.Id;

                public IdUniqueIndex(StengTriggersHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class WorldIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(Trigger row) => row.WorldId;

                public WorldIdIndex(StengTriggersHandle table) : base(table) { }
            }

            public readonly WorldIdIndex WorldId;

            internal StengTriggersHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                WorldId = new(this);
            }

            protected override object GetPrimaryKey(Trigger row) => row.Id;
        }

        public readonly StengTriggersHandle StengTriggers;
    }
}
