// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class StengNavMeshHandle : RemoteTableHandle<EventContext, NavMesh>
        {
            protected override string RemoteTableName => "steng_nav_mesh";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(NavMesh row) => row.Id;

                public IdUniqueIndex(StengNavMeshHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class WorldIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(NavMesh row) => row.WorldId;

                public WorldIdIndex(StengNavMeshHandle table) : base(table) { }
            }

            public readonly WorldIdIndex WorldId;

            internal StengNavMeshHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                WorldId = new(this);
            }

            protected override object GetPrimaryKey(NavMesh row) => row.Id;
        }

        public readonly StengNavMeshHandle StengNavMesh;
    }
}
