// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class StengBehaviorTreeHandle : RemoteTableHandle<EventContext, BehaviorTree>
        {
            protected override string RemoteTableName => "steng_behavior_tree";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(BehaviorTree row) => row.Id;

                public IdUniqueIndex(StengBehaviorTreeHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal StengBehaviorTreeHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(BehaviorTree row) => row.Id;
        }

        public readonly StengBehaviorTreeHandle StengBehaviorTree;
    }
}
