// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class StengNavigationAgentHandle : RemoteTableHandle<EventContext, NavigationAgent>
        {
            protected override string RemoteTableName => "steng_navigation_agent";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(NavigationAgent row) => row.Id;

                public IdUniqueIndex(StengNavigationAgentHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class WorldIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(NavigationAgent row) => row.WorldId;

                public WorldIdIndex(StengNavigationAgentHandle table) : base(table) { }
            }

            public readonly WorldIdIndex WorldId;

            internal StengNavigationAgentHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                WorldId = new(this);
            }

            protected override object GetPrimaryKey(NavigationAgent row) => row.Id;
        }

        public readonly StengNavigationAgentHandle StengNavigationAgent;
    }
}
