// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class StengArchipelagoDataHandle : RemoteTableHandle<EventContext, ArchipelagoData>
        {
            protected override string RemoteTableName => "steng_archipelago_data";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ArchipelagoData row) => row.Id;

                public IdUniqueIndex(StengArchipelagoDataHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class WorldIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(ArchipelagoData row) => row.WorldId;

                public WorldIdIndex(StengArchipelagoDataHandle table) : base(table) { }
            }

            public readonly WorldIdIndex WorldId;

            internal StengArchipelagoDataHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                WorldId = new(this);
            }

            protected override object GetPrimaryKey(ArchipelagoData row) => row.Id;
        }

        public readonly StengArchipelagoDataHandle StengArchipelagoData;
    }
}
