// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class StengRigidBodiesHandle : RemoteTableHandle<EventContext, RigidBody>
        {
            protected override string RemoteTableName => "steng_rigid_bodies";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(RigidBody row) => row.Id;

                public IdUniqueIndex(StengRigidBodiesHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class WorldIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(RigidBody row) => row.WorldId;

                public WorldIdIndex(StengRigidBodiesHandle table) : base(table) { }
            }

            public readonly WorldIdIndex WorldId;

            internal StengRigidBodiesHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                WorldId = new(this);
            }

            protected override object GetPrimaryKey(RigidBody row) => row.Id;
        }

        public readonly StengRigidBodiesHandle StengRigidBodies;
    }
}
