// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class WorldTickHandle : RemoteTableHandle<EventContext, WorldTick>
        {
            protected override string RemoteTableName => "world_tick";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(WorldTick row) => row.Id;

                public IdUniqueIndex(WorldTickHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal WorldTickHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(WorldTick row) => row.Id;
        }

        public readonly WorldTickHandle WorldTick;
    }
}
