// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ZombieUpdateTickHandle : RemoteTableHandle<EventContext, ZombieUpdateTick>
        {
            protected override string RemoteTableName => "zombie_update_tick";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ZombieUpdateTick row) => row.Id;

                public IdUniqueIndex(ZombieUpdateTickHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal ZombieUpdateTickHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(ZombieUpdateTick row) => row.Id;
        }

        public readonly ZombieUpdateTickHandle ZombieUpdateTick;
    }
}
