// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ZombieSpawnTickHandle : RemoteTableHandle<EventContext, ZombieSpawnTick>
        {
            protected override string RemoteTableName => "zombie_spawn_tick";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ZombieSpawnTick row) => row.Id;

                public IdUniqueIndex(ZombieSpawnTickHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal ZombieSpawnTickHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(ZombieSpawnTick row) => row.Id;
        }

        public readonly ZombieSpawnTickHandle ZombieSpawnTick;
    }
}
